# Generated by Django 6.0.2 on 2026-02-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0002_libro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='precio',
        ),
    ]
