# Generated by Django 6.0.2 on 2026-03-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.CharField(choices=[('PAN', 'Pan'), ('QUESO', 'Queso'), ('SALSA', 'Salsa'), ('VEGETAL', 'Vegetal'), ('PROTEINA', 'Proteina'), ('EXTRA', 'Extra')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sandich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='sandwich_de_ingrediente', to='comida_app.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('extras', models.ManyToManyField(related_name='extras_en_pedidos', to='comida_app.ingrediente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comida_app.pedido')),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comida_app.sandich')),
            ],
        ),
    ]
