# Generated by Django 6.0.2 on 2026-03-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sandich',
            new_name='Sandwich',
        ),
    ]
