# Generated by Django 6.0.2 on 2026-03-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida_app', '0002_rename_sandich_sandwich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='extras_en_pedidos', to='comida_app.ingrediente'),
        ),
    ]
