# Generated by Django 6.0.2 on 2026-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida_app', '0003_alter_detallepedido_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
