# Generated by Django 6.0.2 on 2026-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida_app', '0004_pedido_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ingredientes/'),
        ),
    ]
