# Generated by Django 6.0.2 on 2026-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ruta', models.FileField(upload_to='archivo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
